# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.7
    hooks:
      # Run the linter.
      - id: ruff
        exclude_types:
          - pyi
      # Run the formatter.
      - id: ruff-format
        exclude_types:
          - pyi
  - repo: local
    hooks:
      - id: stubgen
        name: Generate Stub files for the module
        entry: poetry run stubgen
        args:
          - -m=si_prefix
          - -o=.
        pass_filenames: false
        language: system
