from matplotlib.ticker import FuncFormatter

class _SiPrefix:
    short_name: str
    long_name: str
    exponent: int
    def __init__(self, short_name: str, long_name: str, exponent: int) -> None: ...
    def get_e_string(self) -> str: ...

SI_PREFIXES: list[_SiPrefix]

def with_format(value: float, precision: int = 1, format_str: str = '{value} {prefix}', exp_format_str: str = '{value}e{exp_of_10}') -> str: ...
def parse(value: str) -> float: ...
def matplotlib_tick_formatter(precision: int = 1, format_str: str = '{value} {prefix}', exp_format_str: str = '{value}e{exp_of_10}') -> FuncFormatter: ...
